# Signatories
<!--
This section provides the ISC with a view of the support received from
the community for a proposal. Acceptance isn't predicated on
popularity but community acceptance is important. Willingness to
accept outside input is also a good marker for project delivery.

An optional section would be for R-Core signatories where changes to R
are proposed.
-->

Members of the [Rbanism community](https://rbanism.org/), represented by Clémentine Cottineau-Mugadza, Daniele Cannatella and Claudiu Forgaci; the [r-spatial community](https://r-spatial.org/), represented by ; the [geocompr community](https://r.geocompx.org/), represented by ; the [ISUF community]() represented by ; and the [SDSL community](https://spatial-data-science.github.io/) represented by have read this proposal and confirm the relevance of this project and its expected high positive impact on the R ecosystem.

## Project team
<!--
Who are the people responsible for actually delivering the project if
the proposal gets accepted and are already signed up and rearing to
go? Briefly describe all participants and the skills they will bring
to the project.
-->

[**Claudiu Forgaci**]() is assistant professor of urban design and analytics engaged in urban morphology research and experienced in R package development (see [rcrisp](https://github.com/CityRiverSpaces/rcrisp), [rcoins](https://github.com/CityRiverSpaces/rcoins), and [visor](https://github.com/CityRiverSpaces/visor)). He is also a member of the Spatial Data Science across Languages (SDSL) community with special interest in cross-language projects. He is also one of the initiators of the [Rbanism community](https://rbanism.org/) promoting reproducibility, automation and scalability in urbanism research using R. Claudiu will lead the development of `momer` and he will maintain it after completion.

[**Elviss Dvinskis**](https://www.tudelft.nl/en/digital-competence-centre/team/elviss-dvinskis) is a research data engineer at the TU Delft Digital Competence Center (DCC). With an extenside [project history](https://www.tudelft.nl/digital-competence-centre/projects) and [expertise](https://www.tudelft.nl/digital-competence-centre/our-expertise), the DCC provides in-kind support for researchers at TU Delft. Elviss will carry out the software engineering work planned in this project with a shared 0.4FTE for the planned duration of the project.

## Contributors
<!--
Who are the people who have actively helped with this proposal but
won't necessarily be on the core project team later?
-->

**Maurits Kok** from Digital Competence Center at TU Delft, the creator of `momepy` **???** and members of the SDSL community **???**, **???** and **???** provided input at the proposal stage. <!--TODO specify content of active help-->

## Consulted
<!--
Who has been given the opportunity to provide feedback on the
proposal? This should include any R Consortium & ISC members who the
proposal has been discussed with.
-->

ISC member **???**<!--**Josiah Parry**--><!--TODO to be contacted-->, also member of the SDSL community, provided feedback on the proposal. <!--TODO specify content of feedback-->

