---
bibliography: references.bib
---

# The Problem

```{=html}
<!--
Outlining the issue / weak point / problem to be solved by this
proposal. This should be a compelling section that sets the reader up
for the next section - the proposed solution!

It is important to cover:

 - [ ] What the problem is
 - [ ] Who it affects
 - [ ] Why is it a problem
 - [ ] What will solving the problem enable (why should it be solved)
 - [ ] Brief summary of existing work and previous attempts (e.g., relevant R packages)
 - [ ] If proposing changes to R itself: letter of support from R Core member
-->
```

Urban morphometrics is a growing sub-field of urban morphology that enables scalable quantitative analysis of urban form. The field of urban morphometrics is inherently programmatic and has been heavily driven and promoted by the Python library [`momepy`](https://docs.momepy.org/en/stable/index.html) [@fleischmann2019]. While `momepy` has played an important role in making the quantitative analysis of urban form accessible to many, it is limited to users of the Python programming language.

Moreover, a large part of urban morphology research is conducted with GUI-based tools and qualitative interpretation, which limits the kind of analytical questions that researchers and practitioners can ask. Automated, reproducible and scalable urban morphology research can only be effectively achieved in a programmatic way. Considering that those three objectives are central to the mission of the Rbanism community which the applicant has co-initiated and which has been growing steadily, `momer` is an opportunity to further promote those standards and enable quantitative research alongside `momepy`.

Currently, a number of R packages provide some functionality for morphometric analysis, but they do not meet the level of comprehensiveness of `momepy`. Most prominent examples are the `foot` package [@foot2021], which focuses on processing building footprints, and the `vectormetrics` package [@matuszek2024], which provides tools for landscape and shape metrics. While the former is limited to building footprint analysis the latter is is only meant to analyse polygon data and is not specifically designed for the analysis of urban form elements.

::: callout-note
Are there any other packages which should be mentioned here?
:::
